version: '1.1'

services:
   postgress : 
     image : postgres:15
     container_name : postgres_db
     envirment :
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1221
      POSTGRES_DB: school
     ports : 
       - '5432:5432'
     volumes : 
       - postgres_data:/var/lib/postgresql/data
      
   app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://postgres:1221d@[YOUR_SERVER_IP]:5432/school
    depends_on:
      - postgres

volumes:
  postgres_data:
